### ISSUE TITLE
Content lost after update to 0.5.4

### ISSUE THREAD

**Issue by dragondaddy** [YunoHost-Apps/zusam_ynh#4]
### Describe the bug

Groups and their content are unaccessible after update to 0.5.4

### Context

Update to 0.5.4 was made by the yunohost-bot

### Steps to reproduce

Update of an existing 0.5.3 install with existing users, groups and content

### Expected behavior

Update to 0.5.4 without losing anything

### Logs

No error logs during install

### Probable solution

Check https://github.com/zusam/zusam/blob/master/documentation/update.md and change 'update' script accordingly

**Comment by dragondaddy** [comment]
No luck so far, asked for help on the app upstream repo (https://github.com/zusam/zusam/issues/58)

**Comment by orhtej2** [comment]
You're missing the following steps from linked docs roughly here: https://github.com/YunoHost-Apps/zusam_ynh/blob/00e87799b98e083dfbee1c1b601e74f05db6a7d9/scripts/upgrade#L35

```
pushd $install_dir
  ynh_exec_as $app  php$phpversion bin/console doctrine:migration:migrate
  ynh_exec_as $app  php$phpversion bin/console zusam:migration
  ynh_install_composer 
  cp app/dist/* public/
popd
```

Generally speaking `install` and `update` scripts should follow similar structure.

**Comment by dragondaddy** [comment]
Still no luck... The update procedure was last updated in April 2022, so maybe some extra steps are necessary.

**Comment by nrobinaubertin** [comment]
To avoid leaving old files that were removed from source in later versions, you should probably use [full_replace](https://github.com/YunoHost/yunohost/blob/5110cd0800faf8f406fe1bc69cb91199f2674a20/helpers/utils#L79)

**Comment by dragondaddy** [comment]
Tried it and it's getting better. Now I'm almost there. I get this line during upgrade:

```
37492 DEBUG  WARNING! You are about to execute a migration in database "main" that could result in schema changes and data loss. Are you sure you wish to continue? (yes/no) [yes]:
```
I need to type yes in order for the upgrade to continue.

Also when I visit the page after the upgrade, all groups appear empty of any content. I can access them using the notifications though, so the groups are still there.

**Comment by nrobinaubertin** [comment]
To avoid having interactions during the migrate command, you can try using `--no-interaction`.  

The issue you're having seems to be some kind of frontend issue. Try to open the developer console when on the group main page (F12 in firefox) and consult the "console" tab to see if there's an error message.  
You can also try to force clear the browser's cache and refresh the page using Ctrl+shift+R

**Comment by dragondaddy** [comment]
Thanks a lot @nrobinaubertin , we seem to be good now. I'll wait for the test results of https://github.com/YunoHost-Apps/zusam_ynh/pull/5 before closing this issue
